# Generated by Django 4.1.6 on 2023-02-07 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_post_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='title',
            field=models.TextField(default=1, help_text='Введите название поста', verbose_name='Название поста'),
            preserve_default=False,
        ),
    ]
