# Generated by Django 4.1.6 on 2023-02-07 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_post_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.CharField(help_text='Введите название поста', max_length=50, verbose_name='Название поста'),
        ),
    ]
