# Generated by Django 4.1.6 on 2023-02-09 08:46

from django.db import migrations
import django_ckeditor_5.fields


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0006_remove_group_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='text',
            field=django_ckeditor_5.fields.CKEditor5Field(help_text='Введите текст поста', verbose_name='Текст поста'),
        ),
    ]
